### PR TITLE
Compress the buffer before uploading on S3

### PR DESCRIPTION
**Pull request by mastermunj**
Added provision to compress the logs before sending them to S3.

### CODE REVIEW

**Comment by autopulated** [comment]
Thanks for contributing, I'd like to understand more the motivation for doing this though, if you can explain?

**Comment by mastermunj** [comment]
To save space on S3 as over a period lot of files will consume huge space increasing cost of storage + retrieval.

In case if anyone wants to use Redshift, Kinesis, MapReduce or Elasticsearch for that matter, compressed files will be faster to read & process.

**Comment by mastermunj** [comment]
@autopulated good to merge?

**Comment by autopulated** [comment]
I've merged this now – there were several things I changed in order to avoid a race condition where data could be lost due to the asynchronous nature of buffer upload.

I also changed the `.gz` extension to be part of the default name format when `compress` is specified, rather than being appended in all cases.

Could you test that what's on master works correctly for your use case? If all looks good I will publish a new minor version.

**Comment by mastermunj** [comment]
Tested. It's working perfect!

Thank you. :)

**Comment by autopulated** [comment]
:+1: published as 1.2.0 :)

**Pull request merged**
