### PR TITLE
change default file_name to `%Y-%m-%d-%H-%M-%S-%L-<current_branch>-<h…

### PR DESCRIPTION
**Pull request by quanvuong**
…ostname>.log`

Kudos to your repo. This is great.

I suggest that the default file name be changed to `%Y-%m-%d-%H-%M-%S-%L-<current_branch>-<hostname>.log`. If `current_branch` is not available, it will be `unknown`.

Thanks!

### CODE REVIEW

**Comment by autopulated** [comment]
Thanks for contributing!

Just a few notes before merging this

 1. git-branch seems to be on version 0.3.0, so we should probably use ~0.3.0 instead of ^0.3.0 

 2. Also, when there's no .git directory present, currently an exception is thrown: 

```
./s3-streamlogger/node_modules/git-branch/index.js:33
    throw new Error('.git/HEAD does not exist.');
    ^
Error: .git/HEAD does not exist.
    at Function.configSync [as sync] (./s3-streamlogger/node_modules/git-branch/index.js:33:11)
    at new S3StreamLogger (./s3-streamlogger/index.js:21:34)
    ...
```

 I'm not sure if there's a different module that could be used to get the branch synchronously without doing that, or I suppose we could just wrap the call in try/catch.

 3. finally, if the `name_format` option is supplied, it's probably best to skip the call to git-branch entirely, since it is a synchronous file system operation which might be quite slow.

**Comment by quanvuong** [comment]
Thanks @autopulated . I implemented the changes you suggested.

**Comment by autopulated** [comment]
Thanks looks good!

This will be a major version change as it might change the file name for someone using the default: it's about time for 1.0 anyway, so I'll publish as version 1.0 soon 👍

**Comment by quanvuong** [comment]
Awesome thank you!

**Pull request merged**
